
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbMain;

	private global::Gtk.Frame frmBase;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vb1OnMain;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label lblBaseAddress;

	private global::Gtk.Entry txtBaseAddress;

	private global::Gtk.Button btnBaseConnect;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView txtViewBase;

	private global::Gtk.Label BasePosLabel;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vb2OnMain;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label lblRoverAddress;

	private global::Gtk.Entry txtRoverAddress;

	private global::Gtk.Button btnRoverConnect;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtViewRover;

	private global::Gtk.Label RoverPosLabel;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.Label lblDistance;

	private global::Gtk.Label DistanceLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbMain = new global::Gtk.VBox();
		this.vbMain.Name = "vbMain";
		this.vbMain.Spacing = 6;
		// Container child vbMain.Gtk.Box+BoxChild
		this.frmBase = new global::Gtk.Frame();
		this.frmBase.Name = "frmBase";
		this.frmBase.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frmBase.BorderWidth = ((uint)(5));
		// Container child frmBase.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vb1OnMain = new global::Gtk.VBox();
		this.vb1OnMain.Name = "vb1OnMain";
		this.vb1OnMain.Spacing = 6;
		// Container child vb1OnMain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblBaseAddress = new global::Gtk.Label();
		this.lblBaseAddress.Name = "lblBaseAddress";
		this.lblBaseAddress.LabelProp = global::Mono.Unix.Catalog.GetString("Base TCP/IP Address:");
		this.hbox1.Add(this.lblBaseAddress);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblBaseAddress]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtBaseAddress = new global::Gtk.Entry();
		this.txtBaseAddress.CanFocus = true;
		this.txtBaseAddress.Name = "txtBaseAddress";
		this.txtBaseAddress.Text = global::Mono.Unix.Catalog.GetString("192.168.1.101:9000");
		this.txtBaseAddress.IsEditable = true;
		this.txtBaseAddress.InvisibleChar = '•';
		this.hbox1.Add(this.txtBaseAddress);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtBaseAddress]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnBaseConnect = new global::Gtk.Button();
		this.btnBaseConnect.CanFocus = true;
		this.btnBaseConnect.Name = "btnBaseConnect";
		this.btnBaseConnect.UseUnderline = true;
		this.btnBaseConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox1.Add(this.btnBaseConnect);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnBaseConnect]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vb1OnMain.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vb1OnMain[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vb1OnMain.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtViewBase = new global::Gtk.TextView();
		this.txtViewBase.CanFocus = true;
		this.txtViewBase.Name = "txtViewBase";
		this.GtkScrolledWindow.Add(this.txtViewBase);
		this.vb1OnMain.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vb1OnMain[this.GtkScrolledWindow]));
		w6.Position = 1;
		this.GtkAlignment.Add(this.vb1OnMain);
		this.frmBase.Add(this.GtkAlignment);
		this.BasePosLabel = new global::Gtk.Label();
		this.BasePosLabel.Name = "BasePosLabel";
		this.BasePosLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Base Position</b>");
		this.BasePosLabel.UseMarkup = true;
		this.frmBase.LabelWidget = this.BasePosLabel;
		this.vbMain.Add(this.frmBase);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbMain[this.frmBase]));
		w9.Position = 0;
		// Container child vbMain.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame2.BorderWidth = ((uint)(5));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vb2OnMain = new global::Gtk.VBox();
		this.vb2OnMain.Name = "vb2OnMain";
		this.vb2OnMain.Spacing = 6;
		// Container child vb2OnMain.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblRoverAddress = new global::Gtk.Label();
		this.lblRoverAddress.Name = "lblRoverAddress";
		this.lblRoverAddress.LabelProp = global::Mono.Unix.Catalog.GetString("Rover TCP/IP Address:");
		this.hbox2.Add(this.lblRoverAddress);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblRoverAddress]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtRoverAddress = new global::Gtk.Entry();
		this.txtRoverAddress.CanFocus = true;
		this.txtRoverAddress.Name = "txtRoverAddress";
		this.txtRoverAddress.Text = global::Mono.Unix.Catalog.GetString("192.168.1.103:9000");
		this.txtRoverAddress.IsEditable = true;
		this.txtRoverAddress.InvisibleChar = '•';
		this.hbox2.Add(this.txtRoverAddress);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.txtRoverAddress]));
		w11.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnRoverConnect = new global::Gtk.Button();
		this.btnRoverConnect.CanFocus = true;
		this.btnRoverConnect.Name = "btnRoverConnect";
		this.btnRoverConnect.UseUnderline = true;
		this.btnRoverConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.hbox2.Add(this.btnRoverConnect);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnRoverConnect]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vb2OnMain.Add(this.hbox2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vb2OnMain[this.hbox2]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vb2OnMain.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtViewRover = new global::Gtk.TextView();
		this.txtViewRover.CanFocus = true;
		this.txtViewRover.Name = "txtViewRover";
		this.GtkScrolledWindow1.Add(this.txtViewRover);
		this.vb2OnMain.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vb2OnMain[this.GtkScrolledWindow1]));
		w15.Position = 1;
		this.GtkAlignment1.Add(this.vb2OnMain);
		this.frame2.Add(this.GtkAlignment1);
		this.RoverPosLabel = new global::Gtk.Label();
		this.RoverPosLabel.Name = "RoverPosLabel";
		this.RoverPosLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Rover Position</b>");
		this.RoverPosLabel.UseMarkup = true;
		this.frame2.LabelWidget = this.RoverPosLabel;
		this.vbMain.Add(this.frame2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbMain[this.frame2]));
		w18.Position = 1;
		// Container child vbMain.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame1.BorderWidth = ((uint)(5));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.lblDistance = new global::Gtk.Label();
		this.lblDistance.Name = "lblDistance";
		this.lblDistance.Ypad = 24;
		this.lblDistance.LabelProp = global::Mono.Unix.Catalog.GetString("{init}");
		this.GtkAlignment2.Add(this.lblDistance);
		this.frame1.Add(this.GtkAlignment2);
		this.DistanceLabel = new global::Gtk.Label();
		this.DistanceLabel.Name = "DistanceLabel";
		this.DistanceLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Distance</b>");
		this.DistanceLabel.UseMarkup = true;
		this.frame1.LabelWidget = this.DistanceLabel;
		this.vbMain.Add(this.frame1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbMain[this.frame1]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.Add(this.vbMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnBaseConnect.Clicked += new global::System.EventHandler(this.OnBtnBaseConnectClicked);
		this.txtViewBase.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnTxtViewBaseSizeAllocated);
		this.btnRoverConnect.Clicked += new global::System.EventHandler(this.OnBtnRoverConnectClicked);
		this.txtViewRover.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnTxtViewRoverSizeAllocated);
	}
}
